import Image from "next/image";
import ContactUsButton from "../buttons/ContactUsButton";



export default function Splash() {
  return (
    <div>
      <div>
        <h1>Unlock Limitless Collaboration and Productivity at CoHive</h1>
        <h2>Step into CoHive, your home for innovative software development. We meticulously build bespoke software solutions that drive your business forward in the digital era.</h2>
        <ContactUsButton />
      </div>
      <Image src='/beehiveimage.jpg' width={500} height={500} alt="beehive" />
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Venenatis tellus in metus vulputate eu scelerisque. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Leo duis ut diam quam nulla porttitor. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Velit laoreet id donec ultrices tincidunt arcu non. Cursus in hac habitasse platea dictumst quisque. Pulvinar sapien et ligula ullamcorper malesuada proin. Scelerisque in dictum non consectetur a erat. Varius sit amet mattis vulputate enim nulla aliquet. Eget nunc lobortis mattis aliquam. Pharetra massa massa ultricies mi quis. A iaculis at erat pellentesque adipiscing commodo elit. Elementum facilisis leo vel fringilla est ullamcorper eget nulla. Tristique magna sit amet purus. Laoreet id donec ultrices tincidunt arcu non.

        Eget dolor morbi non arcu risus quis varius. Sed blandit libero volutpat sed. Interdum consectetur libero id faucibus nisl tincidunt eget nullam non. Sed risus pretium quam vulputate dignissim suspendisse in est ante. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Libero volutpat sed cras ornare arcu. Egestas tellus rutrum tellus pellentesque. Ullamcorper malesuada proin libero nunc. Nulla malesuada pellentesque elit eget gravida. Vitae ultricies leo integer malesuada nunc vel. Consectetur adipiscing elit duis tristique. Tortor vitae purus faucibus ornare. Ut tellus elementum sagittis vitae et leo. Egestas erat imperdiet sed euismod nisi. Bibendum arcu vitae elementum curabitur vitae nunc. Justo eget magna fermentum iaculis. Auctor augue mauris augue neque gravida in fermentum.

        Felis donec et odio pellentesque diam volutpat commodo sed. Pellentesque sit amet porttitor eget dolor morbi. At auctor urna nunc id cursus metus aliquam eleifend. Id diam maecenas ultricies mi eget mauris pharetra et. Aliquam eleifend mi in nulla posuere sollicitudin. Lectus mauris ultrices eros in cursus turpis. Pretium nibh ipsum consequat nisl vel pretium lectus quam id. Diam quam nulla porttitor massa id. A iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Tristique et egestas quis ipsum suspendisse. Eros in cursus turpis massa tincidunt dui ut ornare. Egestas maecenas pharetra convallis posuere morbi leo urna. Quis auctor elit sed vulputate mi sit. Gravida quis blandit turpis cursus in hac. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Tristique magna sit amet purus gravida quis blandit. Eu scelerisque felis imperdiet proin.

        Dui vivamus arcu felis bibendum ut. Non diam phasellus vestibulum lorem sed risus ultricies. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Amet justo donec enim diam vulputate. Massa tempor nec feugiat nisl pretium fusce id. Est ultricies integer quis auctor elit sed vulputate mi. Mi eget mauris pharetra et ultrices. Euismod quis viverra nibh cras pulvinar mattis. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Ultrices neque ornare aenean euismod elementum. Ut enim blandit volutpat maecenas volutpat blandit aliquam. Accumsan lacus vel facilisis volutpat est velit egestas dui. Ac orci phasellus egestas tellus rutrum. Elementum facilisis leo vel fringilla est ullamcorper. Imperdiet dui accumsan sit amet nulla facilisi morbi. Vitae auctor eu augue ut lectus arcu bibendum at varius. Ac felis donec et odio pellentesque diam. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Odio ut sem nulla pharetra diam.

        In tellus integer feugiat scelerisque varius. Magna ac placerat vestibulum lectus mauris. Facilisis magna etiam tempor orci eu lobortis elementum. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Enim tortor at auctor urna nunc id cursus metus aliquam. In metus vulputate eu scelerisque felis imperdiet proin fermentum. Lectus quam id leo in vitae turpis massa sed. Proin libero nunc consequat interdum varius sit. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Est ultricies integer quis auctor elit sed. Enim nulla aliquet porttitor lacus luctus accumsan. Fringilla est ullamcorper eget nulla facilisi etiam.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Venenatis tellus in metus vulputate eu scelerisque. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Leo duis ut diam quam nulla porttitor. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Velit laoreet id donec ultrices tincidunt arcu non. Cursus in hac habitasse platea dictumst quisque. Pulvinar sapien et ligula ullamcorper malesuada proin. Scelerisque in dictum non consectetur a erat. Varius sit amet mattis vulputate enim nulla aliquet. Eget nunc lobortis mattis aliquam. Pharetra massa massa ultricies mi quis. A iaculis at erat pellentesque adipiscing commodo elit. Elementum facilisis leo vel fringilla est ullamcorper eget nulla. Tristique magna sit amet purus. Laoreet id donec ultrices tincidunt arcu non.

        Eget dolor morbi non arcu risus quis varius. Sed blandit libero volutpat sed. Interdum consectetur libero id faucibus nisl tincidunt eget nullam non. Sed risus pretium quam vulputate dignissim suspendisse in est ante. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Libero volutpat sed cras ornare arcu. Egestas tellus rutrum tellus pellentesque. Ullamcorper malesuada proin libero nunc. Nulla malesuada pellentesque elit eget gravida. Vitae ultricies leo integer malesuada nunc vel. Consectetur adipiscing elit duis tristique. Tortor vitae purus faucibus ornare. Ut tellus elementum sagittis vitae et leo. Egestas erat imperdiet sed euismod nisi. Bibendum arcu vitae elementum curabitur vitae nunc. Justo eget magna fermentum iaculis. Auctor augue mauris augue neque gravida in fermentum.

        Felis donec et odio pellentesque diam volutpat commodo sed. Pellentesque sit amet porttitor eget dolor morbi. At auctor urna nunc id cursus metus aliquam eleifend. Id diam maecenas ultricies mi eget mauris pharetra et. Aliquam eleifend mi in nulla posuere sollicitudin. Lectus mauris ultrices eros in cursus turpis. Pretium nibh ipsum consequat nisl vel pretium lectus quam id. Diam quam nulla porttitor massa id. A iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Tristique et egestas quis ipsum suspendisse. Eros in cursus turpis massa tincidunt dui ut ornare. Egestas maecenas pharetra convallis posuere morbi leo urna. Quis auctor elit sed vulputate mi sit. Gravida quis blandit turpis cursus in hac. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Tristique magna sit amet purus gravida quis blandit. Eu scelerisque felis imperdiet proin.

        Dui vivamus arcu felis bibendum ut. Non diam phasellus vestibulum lorem sed risus ultricies. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Amet justo donec enim diam vulputate. Massa tempor nec feugiat nisl pretium fusce id. Est ultricies integer quis auctor elit sed vulputate mi. Mi eget mauris pharetra et ultrices. Euismod quis viverra nibh cras pulvinar mattis. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Ultrices neque ornare aenean euismod elementum. Ut enim blandit volutpat maecenas volutpat blandit aliquam. Accumsan lacus vel facilisis volutpat est velit egestas dui. Ac orci phasellus egestas tellus rutrum. Elementum facilisis leo vel fringilla est ullamcorper. Imperdiet dui accumsan sit amet nulla facilisi morbi. Vitae auctor eu augue ut lectus arcu bibendum at varius. Ac felis donec et odio pellentesque diam. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Odio ut sem nulla pharetra diam.

        In tellus integer feugiat scelerisque varius. Magna ac placerat vestibulum lectus mauris. Facilisis magna etiam tempor orci eu lobortis elementum. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Enim tortor at auctor urna nunc id cursus metus aliquam. In metus vulputate eu scelerisque felis imperdiet proin fermentum. Lectus quam id leo in vitae turpis massa sed. Proin libero nunc consequat interdum varius sit. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Est ultricies integer quis auctor elit sed. Enim nulla aliquet porttitor lacus luctus accumsan. Fringilla est ullamcorper eget nulla facilisi etiam.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Venenatis tellus in metus vulputate eu scelerisque. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Leo duis ut diam quam nulla porttitor. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Velit laoreet id donec ultrices tincidunt arcu non. Cursus in hac habitasse platea dictumst quisque. Pulvinar sapien et ligula ullamcorper malesuada proin. Scelerisque in dictum non consectetur a erat. Varius sit amet mattis vulputate enim nulla aliquet. Eget nunc lobortis mattis aliquam. Pharetra massa massa ultricies mi quis. A iaculis at erat pellentesque adipiscing commodo elit. Elementum facilisis leo vel fringilla est ullamcorper eget nulla. Tristique magna sit amet purus. Laoreet id donec ultrices tincidunt arcu non.

        Eget dolor morbi non arcu risus quis varius. Sed blandit libero volutpat sed. Interdum consectetur libero id faucibus nisl tincidunt eget nullam non. Sed risus pretium quam vulputate dignissim suspendisse in est ante. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Libero volutpat sed cras ornare arcu. Egestas tellus rutrum tellus pellentesque. Ullamcorper malesuada proin libero nunc. Nulla malesuada pellentesque elit eget gravida. Vitae ultricies leo integer malesuada nunc vel. Consectetur adipiscing elit duis tristique. Tortor vitae purus faucibus ornare. Ut tellus elementum sagittis vitae et leo. Egestas erat imperdiet sed euismod nisi. Bibendum arcu vitae elementum curabitur vitae nunc. Justo eget magna fermentum iaculis. Auctor augue mauris augue neque gravida in fermentum.

        Felis donec et odio pellentesque diam volutpat commodo sed. Pellentesque sit amet porttitor eget dolor morbi. At auctor urna nunc id cursus metus aliquam eleifend. Id diam maecenas ultricies mi eget mauris pharetra et. Aliquam eleifend mi in nulla posuere sollicitudin. Lectus mauris ultrices eros in cursus turpis. Pretium nibh ipsum consequat nisl vel pretium lectus quam id. Diam quam nulla porttitor massa id. A iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Tristique et egestas quis ipsum suspendisse. Eros in cursus turpis massa tincidunt dui ut ornare. Egestas maecenas pharetra convallis posuere morbi leo urna. Quis auctor elit sed vulputate mi sit. Gravida quis blandit turpis cursus in hac. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Tristique magna sit amet purus gravida quis blandit. Eu scelerisque felis imperdiet proin.

        Dui vivamus arcu felis bibendum ut. Non diam phasellus vestibulum lorem sed risus ultricies. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Amet justo donec enim diam vulputate. Massa tempor nec feugiat nisl pretium fusce id. Est ultricies integer quis auctor elit sed vulputate mi. Mi eget mauris pharetra et ultrices. Euismod quis viverra nibh cras pulvinar mattis. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Ultrices neque ornare aenean euismod elementum. Ut enim blandit volutpat maecenas volutpat blandit aliquam. Accumsan lacus vel facilisis volutpat est velit egestas dui. Ac orci phasellus egestas tellus rutrum. Elementum facilisis leo vel fringilla est ullamcorper. Imperdiet dui accumsan sit amet nulla facilisi morbi. Vitae auctor eu augue ut lectus arcu bibendum at varius. Ac felis donec et odio pellentesque diam. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Odio ut sem nulla pharetra diam.

        In tellus integer feugiat scelerisque varius. Magna ac placerat vestibulum lectus mauris. Facilisis magna etiam tempor orci eu lobortis elementum. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Enim tortor at auctor urna nunc id cursus metus aliquam. In metus vulputate eu scelerisque felis imperdiet proin fermentum. Lectus quam id leo in vitae turpis massa sed. Proin libero nunc consequat interdum varius sit. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Est ultricies integer quis auctor elit sed. Enim nulla aliquet porttitor lacus luctus accumsan. Fringilla est ullamcorper eget nulla facilisi etiam.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Venenatis tellus in metus vulputate eu scelerisque. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Leo duis ut diam quam nulla porttitor. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Velit laoreet id donec ultrices tincidunt arcu non. Cursus in hac habitasse platea dictumst quisque. Pulvinar sapien et ligula ullamcorper malesuada proin. Scelerisque in dictum non consectetur a erat. Varius sit amet mattis vulputate enim nulla aliquet. Eget nunc lobortis mattis aliquam. Pharetra massa massa ultricies mi quis. A iaculis at erat pellentesque adipiscing commodo elit. Elementum facilisis leo vel fringilla est ullamcorper eget nulla. Tristique magna sit amet purus. Laoreet id donec ultrices tincidunt arcu non.

        Eget dolor morbi non arcu risus quis varius. Sed blandit libero volutpat sed. Interdum consectetur libero id faucibus nisl tincidunt eget nullam non. Sed risus pretium quam vulputate dignissim suspendisse in est ante. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Libero volutpat sed cras ornare arcu. Egestas tellus rutrum tellus pellentesque. Ullamcorper malesuada proin libero nunc. Nulla malesuada pellentesque elit eget gravida. Vitae ultricies leo integer malesuada nunc vel. Consectetur adipiscing elit duis tristique. Tortor vitae purus faucibus ornare. Ut tellus elementum sagittis vitae et leo. Egestas erat imperdiet sed euismod nisi. Bibendum arcu vitae elementum curabitur vitae nunc. Justo eget magna fermentum iaculis. Auctor augue mauris augue neque gravida in fermentum.

        Felis donec et odio pellentesque diam volutpat commodo sed. Pellentesque sit amet porttitor eget dolor morbi. At auctor urna nunc id cursus metus aliquam eleifend. Id diam maecenas ultricies mi eget mauris pharetra et. Aliquam eleifend mi in nulla posuere sollicitudin. Lectus mauris ultrices eros in cursus turpis. Pretium nibh ipsum consequat nisl vel pretium lectus quam id. Diam quam nulla porttitor massa id. A iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Tristique et egestas quis ipsum suspendisse. Eros in cursus turpis massa tincidunt dui ut ornare. Egestas maecenas pharetra convallis posuere morbi leo urna. Quis auctor elit sed vulputate mi sit. Gravida quis blandit turpis cursus in hac. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Tristique magna sit amet purus gravida quis blandit. Eu scelerisque felis imperdiet proin.

        Dui vivamus arcu felis bibendum ut. Non diam phasellus vestibulum lorem sed risus ultricies. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Amet justo donec enim diam vulputate. Massa tempor nec feugiat nisl pretium fusce id. Est ultricies integer quis auctor elit sed vulputate mi. Mi eget mauris pharetra et ultrices. Euismod quis viverra nibh cras pulvinar mattis. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Ultrices neque ornare aenean euismod elementum. Ut enim blandit volutpat maecenas volutpat blandit aliquam. Accumsan lacus vel facilisis volutpat est velit egestas dui. Ac orci phasellus egestas tellus rutrum. Elementum facilisis leo vel fringilla est ullamcorper. Imperdiet dui accumsan sit amet nulla facilisi morbi. Vitae auctor eu augue ut lectus arcu bibendum at varius. Ac felis donec et odio pellentesque diam. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Odio ut sem nulla pharetra diam.

        In tellus integer feugiat scelerisque varius. Magna ac placerat vestibulum lectus mauris. Facilisis magna etiam tempor orci eu lobortis elementum. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Enim tortor at auctor urna nunc id cursus metus aliquam. In metus vulputate eu scelerisque felis imperdiet proin fermentum. Lectus quam id leo in vitae turpis massa sed. Proin libero nunc consequat interdum varius sit. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Est ultricies integer quis auctor elit sed. Enim nulla aliquet porttitor lacus luctus accumsan. Fringilla est ullamcorper eget nulla facilisi etiam.
      </p>
    </div>
  );
  // Contact us button on this view
};